[package]
name = "mygrep"
version = "0.1.0"
edition = "2021"
description = "grep utility written in Rust"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
regex = "1.6"
